```{r, setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

```


## PFTC data repositories

### Data repos

The cleaned datasets from the PFTC courses are stored on an OSF repository (short repo).
Each course has it's own data repo.
The following table shows the link to each of the repos.

| Course  | Country  | Data repo  |
|:---|:---|:---|
| PFTC1 and 2  | China  | [China repo](https://osf.io/f3knq/) |
| PFTC3 and 5  | Peru  | [Peru repo](https://osf.io/gs8u6/) |
| PFTC4  | Svalbard  | [Svalbard repo](https://osf.io/smbqh/) |


### Data paper/documentation

The site, experiment, data collection methods and data dictionaries for each course are described in data papers.
Some information can also be found on the GitHub readme file.

| Course  | Country  | Data paper/documentation  |
|:---|:---|:---|
| PFTC1 and 2  | China  | [Data paper](https://www.nature.com/articles/s41597-020-0529-0) |
| PFTC3 and 5  | Peru  | [GitHub readme](https://github.com/Plant-Functional-Trait-Course/pftc3_punaproject_pftc5) |
| PFTC4  | Svalbard  | [GitHub readme](https://github.com/Plant-Functional-Trait-Course/PFTC_4_Svalbard) |

Read the papers and documentation carefully before using the data.


### Data usage and citation

The data are available for use and teaching purposes under a CC-BY licence.
We suggest to cite the data paper if available, or alternatively the OSF repo.
We appreciate being contacted for advice or collaboration, if relevant, by users of these data.
In cases where our data make up >10% of the data used in a downstream publication, we suggest contacting us for our contribution and collaboration. 
