``` {r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Group projects

## Plastic trait responses to climate change. 

This group will harness existing climate change experiments (Open Top Chambers) to assess plastic trait responses to experimental warming and biotic interactions in plants from alpine vs. warmer-climate origins. This group will collaborate with group 3 to understand how this variability impacts leaf ecophysiology. Group leader: Sonya Geange


## Plant trait responses to global change. 

This group will assess community trait distribution responses to the interactive effects of warmer climate, nitrogen deposition, and grazing along an elevational gradient, and explore consequences for plant community assembly and ecosystem functioning. This group will collaborate with groups 3 and 4 to understand plant and ecosystem functional consequences of these community shifts. Group leaders: Julia Chacon & Aud Halbritter


## Leaf traits as a tool to understand climate impacts on photosynthesis and respiration. 

This group will study how plant temperatures and photosynthetic rates vary between plants with alpine or warmer-climate origin, along elevational gradients, and in response to global change drivers. Group 3 will collaborate with groups 1 and 2 to put these responses in context of broader plant and community responses to global change.  Group leaders: Sean Michaletz & Joseph Garen


## Climate change impacts on traits and ecosystem functioning. 

This group will study how trait composition influences ecosystem functioning by measuring CO2-flux within and across plant communities. Group 4 will collaborate with group 2 to access data on community trait shifts, and mainly focus on ecosystem carbon dynamics in response to climate change, but also nitrogen deposition and grazing. Group leader: Joseph Gaudard


## Remote assessment of plant traits and ecosystem functioning. 

This group will use technologies based on Unmanned Aerial Vehicles (UAV/drone) in combination with measurements from the experiments to assess how remotely-sensed data (e.g., reflectance spectra) can capture plant and ecosystem functional shifts from leaf to landscape-scale. The group will collaborate with groups 1-4 over community-level data. Students applying for this group should have experience with geospatial analyses. Group leaders: Marc Macias-Fauria & Marcus Spiegel (TBC)


## Culturally relevant science communication. 

This group will use questionnaires and interviews to engage with the local community, with the aim of learning their knowledge and perceptions of climate change (especially relevant to local considerations). Group 6 will conduct research locally in Western Norway, compare with results from previous PFTC courses in Peru and Svalbard, and draft a manuscript for publication. Group leader: Sehoya Cotner



