---
title: "PFTC Teaching Material"
author: Aud Halbritter
description: Teaching material for the Plant Functional Trait Courses 
site: bookdown::bookdown_site
documentclass: book
date: "`r Sys.Date()`"
github-repo: Plant-Functional-Trait-Course/PFTC_teaching_material
output:
  bookdown::bs4_book:
    section_numbering: TRUE
    css: "css/style-chapters.css"
---

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)
#, warning = FALSE, error = TRUE
```


# The Plant Functional Trait Course {-}

Our International Plant Functional Traits Courses offer hands-on training in different applications of plant functional traits ecology within a real-life field research project setting. 
Students plan a trait-based research project and field campaign; collect and document plant functional trait data in the field; and explore these data using trait-based approaches within climate change research and ecosystem ecology.

Trait-based ecology incorporates important methods and approaches that enable a powerful approach to predict how climate and biotic interactions shape plant community dynamics and ecosystem functioning. 
This course will provide students with essential background knowledge and the practical field, lab, and computational skills needed for conducting their own research within trait-based ecology.


This book provides the teaching material for the PFTC courses.
